add custom opening and closing tags
mondeja/mkdocs-include-markdown-plugin pull request #112
Opened 2022-07-13 18:04 UTC by supcik

As discussed, here is a PR to allow for custom opening and closing tags

2022-07-13 18:06 UTC, supcik commented
This PR addresses the issue #112

2022-07-13 20:53 UTC, supcik commented
OK... I see that I failed the pre-commit.

I still have some issues with the pre-commit on my machine:

```
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [43 lines of output]
          /Users/.../.cache/pre-commit/repok0ned34x/py_env-default/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
```

and

```
pkgconfig.pkgconfig.PackageNotFoundError: md4c not found
```

I will work on it!

2022-07-13 21:09 UTC, supcik commented
Solved. I had to install _md4c_ with `brew install md4c` (I am on MacOS)

2022-07-13 21:20 UTC, supcik commented
I fixed most of the issues. I am still missing the Spanish translation for the README. I will make one with DeepL

2022-07-14 05:49 UTC, supcik commented
The pre-commit passes on my machine now. Can you please run the workflow again?

2022-07-20 14:18 UTC, mondeja requested changes
Thanks, it's great! Just a couple of suggestions...

2022-07-20 14:18 UTC, mondeja commented on README.md
> +default with the argments `opening_tag` and `closing_tag`:
```suggestion
The default opening and closing tags are `{%` and `%}`. You can change this
default with configuration fields `opening_tag` and `closing_tag`:
```

2022-07-20 14:18 UTC, mondeja commented on mkdocs_include_markdown_plugin/event.py
> +    escaped_closing_tag = escape(closing_tag)
I think that you're reinveting the wheel here, you can use [`re.escape`](https://docs.python.org/3/library/re.html#re.escape):

```suggestion
    escaped_opening_tag = re.escape(opening_tag)
    escaped_closing_tag = re.escape(closing_tag)
```

2022-07-20 18:37 UTC, supcik commented
Thank you for the feedback. I did not know "re.escape", thank you for the tip!

2022-07-21 10:57 UTC, supcik commented
Oups... I accepted your suggestion directly in the browser, so the pre-commit hooks did not run.

2022-07-21 11:59 UTC, mondeja approved these changes
Great!

2022-07-21 12:01 UTC, merged